apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.orientdbConfigMapName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "orientdb-helm.labels" . | nindent 4 }}
  {{- with .Values.configMapAnnotations }}
  annotations:
    {{- toYaml . |  nindent 4 }}
  {{- end}}
data:
  hazelcast.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- ~ Copyright (c) 2008-2012, Hazel Bilisim Ltd. All Rights Reserved. ~
    	~ Licensed under the Apache License, Version 2.0 (the "License"); ~ you may
    	not use this file except in compliance with the License. ~ You may obtain
    	a copy of the License at ~ ~ http://www.apache.org/licenses/LICENSE-2.0 ~
    	~ Unless required by applicable law or agreed to in writing, software ~ distributed
    	under the License is distributed on an "AS IS" BASIS, ~ WITHOUT WARRANTIES
    	OR CONDITIONS OF ANY KIND, either express or implied. ~ See the License for
    	the specific language governing permissions and ~ limitations under the License. -->

    <hazelcast
    		xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.10.xsd"
    		xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    	<group>
    		<name>{{ .Values.hazelcast.group.name }}</name>
    		<password>{{ .Values.hazelcast.group.password }}</password>
    	</group>
    	<properties>
    		<property name="hazelcast.phone.home.enabled">{{ .Values.hazelcast.properties.phoneHomeEnabled }}</property>
    		<property name="hazelcast.mancenter.enabled">{{ .Values.hazelcast.properties.mancenterEnabled }}</property>
    		<property name="hazelcast.memcache.enabled">{{ .Values.hazelcast.properties.memcacheEnabled }}</property>
    		<property name="hazelcast.rest.enabled">{{ .Values.hazelcast.properties.restEnabled }}</property>
    		<property name="hazelcast.wait.seconds.before.join">{{ .Values.hazelcast.properties.waitSecondsBeforeJoin }}</property>
    		<property name="hazelcast.operation.thread.count">{{ .Values.hazelcast.properties.operationThreadCount }}</property>
    		<property name="hazelcast.io.thread.count">{{ .Values.hazelcast.properties.ioThreadCount }}</property>
    		<property name="hazelcast.operation.generic.thread.count">{{ .Values.hazelcast.properties.operationGenericThreadCount }}</property>
    		<property name="hazelcast.client.event.thread.count">{{ .Values.hazelcast.properties.clientEventThreadCount }}</property>
    		<property name="hazelcast.event.thread.count">{{ .Values.hazelcast.properties.eventThreadCount }}</property>
    		<property name="hazelcast.heartbeat.interval.seconds">{{ .Values.hazelcast.properties.heartbeatIntervalSeconds }}</property>
    		<property name="hazelcast.max.no.heartbeat.seconds">{{ .Values.hazelcast.properties.maxNoHeartbeatSeconds }}</property>
    		<property name="hazelcast.merge.next.run.delay.seconds">{{ .Values.hazelcast.properties.mergeNextRunDelaySeconds }}</property>
    	</properties>
    	<network>
    		<port auto-increment="false">{{ .Values.hazelcast.network.port }}</port>
    		<join>
    			<kubernetes enabled="true">
                   <pod-label-name>{{ .Values.hazelcast.discovery.podLabel.name }}</pod-label-name>
                   <pod-label-value>{{ .Values.hazelcast.discovery.podLabel.value }}</pod-label-value>
                   <service-port>{{ .Values.hazelcast.network.port }}</service-port>
                   <namespace>{{ .Values.namespace }}</namespace>
                </kubernetes>
                <multicast enabled="false">
                </multicast>
    		</join>
    	</network>
    	<executor-service>
    		<pool-size>16</pool-size>
    	</executor-service>
    </hazelcast>

  default-distributed-db-config.json: |
    {
      "autoDeploy": {{ .Values.distributedDB.defaultConfig.autoDeploy }},
      "readQuorum": {{ .Values.distributedDB.defaultConfig.readQuorum }},
      "writeQuorum": "{{ .Values.distributedDB.defaultConfig.writeQuorum }}",
      "readYourWrites": {{ .Values.distributedDB.defaultConfig.readYourWrites }},
      "newNodeStrategy": "{{ .Values.distributedDB.defaultConfig.newNodeStrategy }}",
      "servers": {
        "*": "master"
      },
      "clusters": {
        "internal": {
        },
        "*": {
          "servers": ["<NEW_NODE>"]
        }
      }
    }

  orientdb-server-config.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <orient-server>
        <handlers>
            <handler class="com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin">
                <parameters>
                    <!-- <parameter name="nodeName" value="europe1" /> -->
                    <parameter name="enabled" value="${distributed}"/>
                    <parameter name="configuration.db.default"
                               value="${ORIENTDB_HOME}/config/default-distributed-db-config.json"/>
                    <parameter name="configuration.hazelcast" value="${ORIENTDB_HOME}/config/hazelcast.xml"/>
                </parameters>
            </handler>
            <!-- JMX SERVER, TO TURN ON SET THE 'ENABLED' PARAMETER TO 'true' -->
            <handler class="com.orientechnologies.orient.server.handler.OJMXPlugin">
                <parameters>
                    <parameter name="enabled" value="false"/>
                    <parameter name="profilerManaged" value="true"/>
                </parameters>
            </handler>
            <!-- AUTOMATIC BACKUP, TO TURN ON SET THE 'ENABLED' PARAMETER TO 'true' -->
            <handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
                <parameters>
                    <parameter name="enabled" value="{{ .Values.automaticBackup.enabled }}"/>
                    <!-- LOCATION OF JSON CONFIGURATION FILE -->
                    <parameter name="config" value="${ORIENTDB_HOME}/config/automatic-backup.json"/>
                </parameters>
            </handler>
            <!-- SERVER SIDE SCRIPT INTERPRETER. WARNING, THIS CAN BE A SECURITY HOLE BECAUSE MALICIOUS CODE COULD BE INJECTED.
                ENABLE IT ONLY IF CLIENTS ARE TRUSTED, TO TURN ON SET THE 'ENABLED' PARAMETER TO 'true' -->
            <handler
                    class="com.orientechnologies.orient.server.handler.OServerSideScriptInterpreter">
                <parameters>
                    <parameter name="enabled" value="{{ .Values.serverSideScript.enabled }}"/>
                    <parameter name="allowedLanguages" value="{{ join "," .Values.serverSideScript.allowedLanguages }}"/>
                    <!--  Comma separated packages  allowed in JS scripts eg. java.math.*, java.util.ArrayList -->
                    <parameter name="allowedPackages" value=""/>
                </parameters>
            </handler>
            <!-- CUSTOM SQL FUNCTIONS -->
            <handler class="com.orientechnologies.orient.server.handler.OCustomSQLFunctionPlugin">
                <parameters>
                    <!-- LOCATION OF JSON CONFIGURATION FILE -->
                    <parameter name="config" value="${ORIENTDB_HOME}/config/custom-sql-functions.json"/>
                </parameters>
            </handler>

        </handlers>
        <network>
            <sockets>
                <socket implementation="com.orientechnologies.orient.server.network.OServerTLSSocketFactory" name="ssl">
                    <parameters>
                        <parameter value="{{ .Values.ssl.clientAuth }}" name="network.ssl.clientAuth"/>
                        <parameter value="{{ .Values.ssl.keyStore }}" name="network.ssl.keyStore"/>
                        <parameter value="{{ .Values.ssl.keyStorePassword }}" name="network.ssl.keyStorePassword"/>
                        <parameter value="{{ .Values.ssl.trustStore }}" name="network.ssl.trustStore"/>
                        <parameter value="{{ .Values.ssl.trustStorePassword }}" name="network.ssl.trustStorePassword"/>
                    </parameters>
                </socket>
                <socket implementation="com.orientechnologies.orient.server.network.OServerTLSSocketFactory" name="https">
                    <parameters>
                        <parameter value="{{ .Values.ssl.clientAuth }}" name="network.ssl.clientAuth"/>
                        <parameter value="{{ .Values.ssl.keyStore }}" name="network.ssl.keyStore"/>
                        <parameter value="{{ .Values.ssl.keyStorePassword }}" name="network.ssl.keyStorePassword"/>
                        <parameter value="{{ .Values.ssl.trustStore }}" name="network.ssl.trustStore"/>
                        <parameter value="{{ .Values.ssl.trustStorePassword }}" name="network.ssl.trustStorePassword"/>
                    </parameters>
                </socket>
            </sockets>
            <protocols>
                <!-- Default registered protocol. It reads commands using the HTTP protocol and write data locally -->
                <protocol name="binary"
                          implementation="com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary"/>
                <protocol name="http"
                          implementation="com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpDb"/>
            </protocols>
            <listeners>
                <listener protocol="binary" ip-address="0.0.0.0" port-range="{{ .Values.binaryPort }}" socket="default"/>
                {{- if .Values.ssl.enable }}
                <listener protocol="binary" ip-address="0.0.0.0" port-range="{{ .Values.binarySslPort }}" socket="ssl"/>
                <listener protocol="http" ip-address="0.0.0.0" port-range="{{ .Values.httpsPort }}" socket="https">
                {{- else }}
                <listener protocol="http" ip-address="0.0.0.0" port-range="{{ .Values.httpPort }}" socket="default">
                {{- end }}
                    <parameters>
                        <!-- Connection's custom parameters. If not specified the global configuration will be taken -->
                        <parameter name="network.http.charset" value="utf-8"/>
                        <parameter value="true" name="network.http.jsonResponseError"/>
                        <parameter value="Content-Security-Policy: frame-ancestors 'none'" name="network.http.additionalResponseHeaders"></parameter>
                        <!-- Define additional HTTP headers to always send as response -->
                        <!-- Allow cross-site scripting -->
                        <!-- parameter name="network.http.additionalResponseHeaders" value="Access-Control-Allow-Origin:
                            *;Access-Control-Allow-Credentials: true" / -->
                    </parameters>
                    <commands>
                        <command
                                pattern="GET|www GET|studio/ GET| GET|*.htm GET|*.html GET|*.xml GET|*.jpeg GET|*.jpg GET|*.png GET|*.gif GET|*.js GET|*.css GET|*.swf GET|*.ico GET|*.txt GET|*.otf GET|*.pjs GET|*.svg GET|*.json GET|*.woff GET|*.woff2 GET|*.ttf GET|*.svgz"
                                implementation="com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetStaticContent">
                            <parameters>
                                <!-- Don't cache html resources in development mode -->
                                <entry name="http.cache:*.htm *.html"
                                       value="Cache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache"/>
                                <!-- Default caching -->
                                <entry name="http.cache:default" value="Cache-Control: max-age=120"/>
                            </parameters>
                        </command>
                        <command pattern="GET|gephi/*"
                                 implementation="com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetGephi"/>

                    </commands>
                </listener>
            </listeners>
            <cluster>
            </cluster>
        </network>
        <storages>
        </storages>
        <users>
          {{- if .Values.createRootUser -}}
          <user resources="*" password="{{ .Values.rootPassword }}" name="root"/>
          {{- end -}}
        </users>
        <properties>
            <!-- PROFILER: configures the profiler as <seconds-for-snapshot>,<archive-snapshot-size>,<summary-size> -->
            <entry name="profiler.enabled" value="false"/>
            <!-- <entry name="profiler.config" value="30,10,10" /> -->
        </properties>
    </orient-server>

  orientdb-server-log.properties: |
    {{- include "orientdb-helm.log-properties" . | nindent 4 }}
  custom-sql-functions.json: |
    {
      "enabled": {{ .Values.customSqlFunctions.enabled }},
      "functions": [
        //    {
        //      "prefix": "the_function_prefix here",
        //      "class": "your.class.with.static.methods.Here"
        //    }
      ]
    }
  automatic-backup.json: |
    {{- include "orientdb-helm.auto-backup-config" . | nindent 4 }}
  security.json: |
    {{- include "orientdb-helm.security-config" . | nindent 4 }}