{{- if .Values.ssl.enable -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssl.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "orientdb-helm.labels" . | nindent 4 }}
  {{- with .Values.ssl.secretAnnotations }}
  annotations:
    {{- toYaml . |  nindent 4 }}
  {{- end}}
type: Opaque
data:
  orientdb.ks: |-
    {{ .Files.Get .Values.ssl.keyStoreFile | b64enc }}
  orientdb.ts: |-
    {{ .Files.Get .Values.ssl.trustStoreFile | b64enc }}
{{- end -}}