FROM kong:2.3.2
LABEL description="Alpine + Kong + kong-oidc plugin"

USER root
RUN apk update && apk add git unzip luarocks git
RUN git clone https://github.com/SebastienDorgan/kong-oidc.git
RUN cd kong-oidc && luarocks make
USER kong