apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hiveMetastore.fullname" . }}-hadoop
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}-hadoop
    {{- include "hiveMetastore.labels" . | nindent 4 }}
data:
  core-site.xml: |
    <configuration>
      <property>
        <name>alluxio.master.rpc.addresses</name>
        <value>alluxio-master-0:19998</value>
      </property>
    </configuration>