---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${username}-user
  namespace: ${username}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ${username}-user-full-access
  namespace: ${username}
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ${username}-user-view
  namespace: ${username}
subjects:
- kind: ServiceAccount
  name: ${username}-user
  namespace: ${username}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${username}-user-full-access