apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume-${storage_class_name}
spec:
  capacity:
    storage: ${size}Gi
  storageClassName: ${storage_class_name}
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /data/shared-data